server:
  port: 8081
  servlet:
    context-path: /zsxspring

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true & characterEncoding=utf-8 &
      useSSL=true & serverTimezone=Asia/Shanghai
    username: root
    password: 330825

  application:
    name: zsxspring
  boot:
    admin:
      client:
        url: http://localhost:8090
        username: zsx
        password: 330825

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: zsx.entity

management:
  endpoints:
    web:
      exposure:
        include: '*'